---
title: "pds08_2.Rmd"
author: "Braden T Tierney"
date: "10/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(umap)
library(cowplot)
library(vegan)
library(ggrepel)

theme_set(theme_cowplot())
```


CONSTIPATED COHORT

```{r}

setwd('~/Desktop/google_drive/My Drive/pds08/')

system("mkdir alternative_cohorts/constipated_cohort/metaphlan_associations/scatterplots/")

baseline_data = readRDS('metaphlan_baseline.rds')
delta_data = readRDS('metaphlan_delta.rds')
endpoint_data = readRDS('metaphlan_endpoint.rds')

colnames(baseline_data) = gsub("^.*\\|", "", colnames(baseline_data))
colnames(delta_data) = gsub("^.*\\|", "", colnames(delta_data))
colnames(endpoint_data) = gsub("^.*\\|", "", colnames(endpoint_data))

metadata = readRDS('pds08_metadata.rds') %>% filter(b_bm_weekly<=4.2)

cohort_summary = read.csv('alternative_cohorts/constipated_cohort/metaphlan_associations/regression_output.csv') %>% filter(bh<.1) %>% select(term,tp,dependent_var)

for(ind in seq(1,nrow(cohort_summary))){
  val = cohort_summary[ind,]
  bug = val[[1]] %>% unlist %>% unname
  tp = val[[2]] %>% unlist %>% unname
  depvar = val[[3]] %>% unlist %>% unname
  if(tp == 'baseline'){
    temp = left_join(metadata,baseline_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=log(temp[,bug]+0.0001))) + geom_point() + xlab(depvar) + ylab('ln(abundance)') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/constipated_cohort/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'delta'){
    temp = left_join(metadata,delta_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=temp[,bug])) + geom_point()+ xlab(depvar) + ylab('change in abundance') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/constipated_cohort/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'endpoint'){
    temp = left_join(metadata,endpoint_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=log(temp[,bug]+0.0001))) + geom_point() + xlab(depvar) + ylab('ln(abundance)') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/constipated_cohort/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
}

baseline_data = readRDS('metaphlan_baseline_diversity.rds')
delta_data = readRDS('metaphlan_delta_diversity.rds')
endpoint_data = readRDS('metaphlan_endpoint_diversity.rds')

metadata = readRDS('pds08_metadata.rds') %>% filter(b_bm_weekly<=4.2)

cohort_summary = read.csv('alternative_cohorts/constipated_cohort/metaphlan_associations/diversity_clinical.csv') %>% filter(p.value<0.05) %>% select(term,tp,dependent_var)

for(ind in seq(1,nrow(cohort_summary))){
  val = cohort_summary[ind,]
  bug = val[[1]] %>% unlist %>% unname
  tp = val[[2]] %>% unlist %>% unname
  depvar = val[[3]] %>% unlist %>% unname
  if(tp == 'baseline'){
    temp = left_join(metadata,baseline_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=(temp[,bug]))) + geom_point() + xlab(depvar) + ylab('diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/constipated_cohort/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'delta'){
    temp = left_join(metadata,delta_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=temp[,bug])) + geom_point()+ xlab(depvar) + ylab('change in diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/constipated_cohort/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'endpoint'){
    temp = left_join(metadata,endpoint_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=(temp[,bug]))) + geom_point() + xlab(depvar) + ylab('diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/constipated_cohort/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
}
 
```

FULL COHORT

```{r}

setwd('~/Desktop/google_drive/My Drive/pds08/')

system("mkdir alternative_cohorts/full_cohort/metaphlan_associations/scatterplots/")

baseline_data = readRDS('metaphlan_baseline.rds')
delta_data = readRDS('metaphlan_delta.rds')
endpoint_data = readRDS('metaphlan_endpoint.rds')

colnames(baseline_data) = gsub("^.*\\|", "", colnames(baseline_data))
colnames(delta_data) = gsub("^.*\\|", "", colnames(delta_data))
colnames(endpoint_data) = gsub("^.*\\|", "", colnames(endpoint_data))

metadata = readRDS('pds08_metadata.rds') 

cohort_summary = read.csv('alternative_cohorts/full_cohort/metaphlan_associations/regression_output.csv') %>% filter(bh<.1) %>% select(term,tp,dependent_var)

for(ind in seq(1,nrow(cohort_summary))){
  val = cohort_summary[ind,]
  bug = val[[1]] %>% unlist %>% unname
  tp = val[[2]] %>% unlist %>% unname
  depvar = val[[3]] %>% unlist %>% unname
  if(tp == 'baseline'){
    temp = left_join(metadata,baseline_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=log(temp[,bug]+0.0001))) + geom_point() + xlab(depvar) + ylab('ln(abundance)') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/full_cohort/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'delta'){
    temp = left_join(metadata,delta_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=temp[,bug])) + geom_point()+ xlab(depvar) + ylab('change in abundance') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/full_cohort/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'endpoint'){
    temp = left_join(metadata,endpoint_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=log(temp[,bug]+0.0001))) + geom_point() + xlab(depvar) + ylab('ln(abundance)') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/full_cohort/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
}
 
baseline_data = readRDS('metaphlan_baseline_diversity.rds')
delta_data = readRDS('metaphlan_delta_diversity.rds')
endpoint_data = readRDS('metaphlan_endpoint_diversity.rds')

metadata = readRDS('pds08_metadata.rds') %>% filter(b_bm_weekly<=4.2)

cohort_summary = read.csv('alternative_cohorts/full_cohort/metaphlan_associations/diversity_clinical.csv') %>% filter(p.value<0.05) %>% select(term,tp,dependent_var)

for(ind in seq(1,nrow(cohort_summary))){
  val = cohort_summary[ind,]
  bug = val[[1]] %>% unlist %>% unname
  tp = val[[2]] %>% unlist %>% unname
  depvar = val[[3]] %>% unlist %>% unname
  if(tp == 'baseline'){
    temp = left_join(metadata,baseline_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=(temp[,bug]))) + geom_point() + xlab(depvar) + ylab('diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/full_cohort/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'delta'){
    temp = left_join(metadata,delta_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=temp[,bug])) + geom_point()+ xlab(depvar) + ylab('change in diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/full_cohort/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'endpoint'){
    temp = left_join(metadata,endpoint_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=(temp[,bug]))) + geom_point() + xlab(depvar) + ylab('diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/full_cohort/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
}
```

FULL LOGGED COHORT

```{r}

setwd('~/Desktop/google_drive/My Drive/pds08/')

system("mkdir alternative_cohorts/non_constipated_logged/metaphlan_associations/scatterplots/")

baseline_data = readRDS('metaphlan_baseline.rds')
delta_data = readRDS('metaphlan_delta.rds')
endpoint_data = readRDS('metaphlan_endpoint.rds')

colnames(baseline_data) = gsub("^.*\\|", "", colnames(baseline_data))
colnames(delta_data) = gsub("^.*\\|", "", colnames(delta_data))
colnames(endpoint_data) = gsub("^.*\\|", "", colnames(endpoint_data))

metadata = readRDS('pds08_metadata.rds')%>% mutate(b_bm_weekly = log(b_bm_weekly),bm_weekly = log(bm_weekly), d_bm_weekly = log(d_bm_weekly))

cohort_summary = read.csv('alternative_cohorts/non_constipated_logged/metaphlan_associations/regression_output.csv') %>% filter(bh<.1) %>% select(term,tp,dependent_var)

for(ind in seq(1,nrow(cohort_summary))){
  val = cohort_summary[ind,]
  bug = val[[1]] %>% unlist %>% unname
  tp = val[[2]] %>% unlist %>% unname
  depvar = val[[3]] %>% unlist %>% unname
  if(tp == 'baseline'){
    temp = left_join(metadata,baseline_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=log(temp[,bug]+0.0001))) + geom_point() + xlab(depvar) + ylab('ln(abundance)') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/non_constipated_logged/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'delta'){
    temp = left_join(metadata,delta_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=temp[,bug])) + geom_point()+ xlab(depvar) + ylab('change in abundance') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/non_constipated_logged/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'endpoint'){
    temp = left_join(metadata,endpoint_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=log(temp[,bug]+0.0001))) + geom_point() + xlab(depvar) + ylab('ln(abundance)') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/non_constipated_logged/metaphlan_associations/scatterplots/',depvar,'_',tp,'_',bug,'.pdf',sep=''),width=6,height=6)
  }
}
 
baseline_data = readRDS('metaphlan_baseline_diversity.rds')
delta_data = readRDS('metaphlan_delta_diversity.rds')
endpoint_data = readRDS('metaphlan_endpoint_diversity.rds')

metadata = readRDS('pds08_metadata.rds') %>% filter(b_bm_weekly<=4.2)

cohort_summary = read.csv('alternative_cohorts/non_constipated_logged/metaphlan_associations/diversity_clinical.csv') %>% filter(p.value<0.05) %>% select(term,tp,dependent_var)

for(ind in seq(1,nrow(cohort_summary))){
  val = cohort_summary[ind,]
  bug = val[[1]] %>% unlist %>% unname
  tp = val[[2]] %>% unlist %>% unname
  depvar = val[[3]] %>% unlist %>% unname
  if(tp == 'baseline'){
    temp = left_join(metadata,baseline_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=(temp[,bug]))) + geom_point() + xlab(depvar) + ylab('diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/non_constipated_logged/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'delta'){
    temp = left_join(metadata,delta_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=temp[,bug])) + geom_point()+ xlab(depvar) + ylab('change in diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/non_constipated_logged/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
  if(tp == 'endpoint'){
    temp = left_join(metadata,endpoint_data,by='Sample_ID')
    ggplot(data = temp, aes(x=temp[,depvar],y=(temp[,bug]))) + geom_point() + xlab(depvar) + ylab('diversity') + ggtitle(bug)
      ggsave(paste('alternative_cohorts/non_constipated_logged/metaphlan_associations/',depvar,'_',tp,'_',bug,'diversity.pdf',sep=''),width=6,height=6)
  }
}
```

```{r}
# comparing bug of interest abundance at baseline vs endpoint

setwd('~/Desktop/google_drive/My Drive/pds08/')

baseline_data = readRDS('metaphlan_baseline.rds')
delta_data = readRDS('metaphlan_delta.rds')
endpoint_data = readRDS('metaphlan_endpoint.rds')

colnames(baseline_data) = gsub("^.*\\|", "", colnames(baseline_data))
colnames(delta_data) = gsub("^.*\\|", "", colnames(delta_data))
colnames(endpoint_data) = gsub("^.*\\|", "", colnames(endpoint_data))

metadata = readRDS('pds08_metadata.rds')

bugs_of_interest = c("Sample_ID","s__Lactobacillus_rhamnosus","s__Lactobacillus_acidophilus",'s__Bifidobacterium_longum',"s__Bifidobacterium_breve")

baseline_data = left_join(baseline_data,metadata,by='Sample_ID') %>% mutate (timepoint = 'baseline') %>% select(all_of(bugs_of_interest),rx,timepoint)
delta_data = left_join(delta_data,metadata,by='Sample_ID')  %>% mutate (timepoint = 'delta')%>% select(all_of(bugs_of_interest),rx,timepoint)
endpoint_data = left_join(endpoint_data,metadata,by='Sample_ID') %>% mutate (timepoint = 'endpoint')%>% select(all_of(bugs_of_interest),rx,timepoint)

merged = bind_rows(baseline_data,endpoint_data) %>% filter(!is.na(rx))

ggplot(data = merged,aes(x = as.factor(timepoint),y = log(s__Lactobacillus_rhamnosus+0.00001))) + geom_point(aes(color=rx)) +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ geom_line(aes(group=Sample_ID)) + ylab('ln(abundance)') + ggtitle('Lactobacillus_rhamnosus')

ggsave('lrham_change.pdf',width=6,height=6)

ggplot(data = merged,aes(x = as.factor(timepoint),y = log(s__Lactobacillus_acidophilus+0.00001))) + geom_point(aes(color=rx)) +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ geom_line(aes(group=Sample_ID)) + ylab('ln(abundance)') + ggtitle('Lactobacillus_acidophilus')

ggsave('lacido_change.pdf',width=6,height=6)

ggplot(data = merged,aes(x = as.factor(timepoint),y = log(s__Bifidobacterium_longum+0.00001))) +geom_point(aes(color=rx)) +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ geom_line(aes(group=Sample_ID)) + ylab('ln(abundance)') + ggtitle('Bifidobacterium_longum')

ggsave('blongum_change.pdf',width=6,height=6)

ggplot(data = merged,aes(x = as.factor(timepoint),y = log(s__Bifidobacterium_breve+0.00001))) + geom_point(aes(color=rx)) +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ geom_line(aes(group=Sample_ID)) + ylab('ln(abundance)') + ggtitle('Bifidobacterium_breve')

ggsave('bbreve_change.pdf',width=6,height=6)

```









