---
title: "pds08_pathways"
author: "Braden T Tierney"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(umap)
library(cowplot)
library(vegan)
library(ggrepel)

theme_set(theme_cowplot())
```

```{r}
# init 
setwd('~/Desktop/google_drive/My Drive/pds08/')

system('mkdir pathways_associations/volcano_plots_delta')
system('mkdir pathways_associations/volcano_plots_endpoint')
system('mkdir pathways_associations/volcano_plots_baseline')

system('mkdir pathways_associations/volcano_plots_baseline_interaction')
system('mkdir pathways_associations/volcano_plots_delta_interaction')
system('mkdir pathways_associations/volcano_plots_endpoint_interaction')
```

```{r}
#UMAP BASELINE, DELTA, ENDPOINT

setwd('~/Desktop/google_drive/My Drive/pds08/')

baseline_pathways = readRDS('pathways_baseline.rds') %>% mutate(Sample_ID = paste(Sample_ID,'_baseline',sep=''))
endpoint_pathways = readRDS('pathways_endpoint.rds') %>% mutate(Sample_ID = paste(Sample_ID,'_endpoint',sep=''))
delta_pathways = readRDS('pathways_delta.rds') %>% mutate(Sample_ID = paste(Sample_ID,'_delta',sep=''))

metadata = readRDS('pds08_metadata.rds')

pathways_b_e = bind_rows(baseline_pathways,endpoint_pathways) %>% column_to_rownames('Sample_ID') 
pathways_b_e_umap = umap(pathways_b_e)

umap_output = pathways_b_e_umap$layout %>% data.frame %>% rownames_to_column('key') %>% as.tibble %>% mutate(Sample_ID = strsplit(key,'_') %>% map_chr(1),timepoint = strsplit(key,'_') %>% map_chr(2))
umap_output = left_join(umap_output,metadata,by='Sample_ID')

ggplot(data = umap_output %>% filter(timepoint == 'baseline'),aes(x=X1,y=X2,group=Sample_ID,color=(b_bm_weekly))) + geom_point(size=3,aes(shape=timepoint)) + geom_line(color='grey') 
ggplot(data = umap_output %>% filter(timepoint == 'endpoint'),aes(x=X1,y=X2,group=Sample_ID,color=(bm_weekly))) + geom_point(size=3,aes(shape=timepoint)) + geom_line(color='grey') 
ggplot(data = umap_output,aes(x=X1,y=X2,group=Sample_ID,color=(bm_weekly))) + geom_point(size=3,aes(shape=timepoint)) + geom_line(color='grey') 

delta_pathways = delta_pathways %>% column_to_rownames('Sample_ID') 
pathways_delta_umap = umap(pathways_b_e)

umap_output = pathways_delta_umap$layout %>% data.frame %>% rownames_to_column('key') %>% as.tibble %>% mutate(Sample_ID = strsplit(key,'_') %>% map_chr(1),timepoint = strsplit(key,'_') %>% map_chr(2))
umap_output = left_join(umap_output,metadata,by='Sample_ID')

ggplot(data = umap_output,aes(x=X1,y=X2,group=Sample_ID,color=(d_bm_weekly))) + geom_point(size=3,aes(shape=rx))

#pca = prcomp(pathways_b_e %>% t,center = T)
#pathways_b_e_pca = pca$rotation[,1:5]

#pathways_b_e_pca = pathways_b_e_pca%>% data.frame %>% rownames_to_column('key') %>% as.tibble %>% mutate(Sample_ID = strsplit(key,'_') %>% map_chr(1),timepoint = strsplit(key,'_') %>% map_chr(2))
#pca_output = left_join(pathways_b_e_pca,metadata,by='Sample_ID')

#ggplot(data = pca_output,aes(x=PC1,y=PC2,group=Sample_ID,color=as.factor(rx))) + geom_point(aes(shape=timepoint)) + geom_line(color='grey')

```

```{r}
# beta diversity 
setwd('~/Desktop/google_drive/My Drive/pds08/')

baseline_pathways = readRDS('pathways_baseline.rds') %>% column_to_rownames('Sample_ID') 
endpoint_pathways = readRDS('pathways_endpoint.rds')   %>% column_to_rownames('Sample_ID') 
delta_pathways = readRDS('pathways_delta.rds')  %>% column_to_rownames('Sample_ID') 

metadata = readRDS('pds08_metadata.rds')  %>% column_to_rownames('Sample_ID') 
metadata$d_bm1 = as.factor(metadata$d_bm1)
metadata$d_bm2 = as.factor(metadata$d_bm2)
metadata$d_bm3 = as.factor(metadata$d_bm3)
metadata$d_bristol = as.factor(metadata$d_bristol)

metadata = metadata[rownames(baseline_pathways),]
# baseline
beta_dist = as.matrix(vegdist(baseline_pathways,index = "bray"))

pheatmap::pheatmap(mat = beta_dist, show_rownames = F,show_colnames = T,cluster_rows=T,cluster_cols =T,annotation_row = metadata %>% select(bristol,d_bm3,rx))

# endpoint
beta_dist = as.matrix(vegdist(endpoint_pathways,index = "bray"))

pheatmap::pheatmap(mat = beta_dist, show_rownames = F,show_colnames = T,cluster_rows=T,cluster_cols =T,annotation_row = metadata %>% select(bristol,d_bm3,rx))
```

```{r}
# alpha diversity -- baseline, clinical variables
setwd('~/Desktop/google_drive/My Drive/pds08/')

baseline = list.files('pathways_associations')
baseline = baseline[grep('baseline',baseline)]
baseline = baseline[grep('diversity',baseline)]
baseline = baseline[grep('pathways',baseline)]
baseline = baseline[grep('outcome',baseline)]
endpoint = endpoint[-grep('interaction',endpoint)]

data = list()
for(f in baseline){
  d = readRDS(paste('pathways_associations/',f,sep='')) %>% mutate(var = gsub('_pathways_baseline_diversity.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

bind_rows(data)%>% filter(p.value<0.1)
```

```{r}
# alpha diversity -- delta, clinical variables
setwd('~/Desktop/google_drive/My Drive/pds08/')

delta = list.files('pathways_associations')
delta = delta[grep('delta',delta)]
delta = delta[grep('diversity',delta)]
delta = delta[grep('pathways',delta)]
delta = delta[grep('outcome',delta)]
endpoint = endpoint[-grep('interaction',endpoint)]

data = list()
for(f in delta){
  d = readRDS(paste('pathways_associations/',f,sep='')) %>% mutate(var = gsub('_pathways_delta_diversity.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

bind_rows(data) %>% filter(p.value<0.1)
```

```{r}
# alpha diversity -- endpoint, clinical variables
setwd('~/Desktop/google_drive/My Drive/pds08/')

endpoint = list.files('pathways_associations')
endpoint = endpoint[grep('endpoint',endpoint)]
endpoint = endpoint[grep('diversity',endpoint)]
endpoint = endpoint[grep('pathways',endpoint)]
endpoint = endpoint[grep('outcome',endpoint)]

data = list()
for(f in endpoint){
  d = readRDS(paste('pathways_associations/',f,sep='')) %>% mutate(var = gsub('_pathways_endpoint_diversity.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

bind_rows(data) %>% filter(p.value<0.1)
```

```{r}
# alpha diversity -- treatment
setwd('~/Desktop/google_drive/My Drive/pds08/')

baseline_alpha = readRDS('./pathways_associations/regression_output_microbe_treatment_pathways_baseline_diversity.rds') %>% mutate()
endpoint_alpha = readRDS('./pathways_associations/regression_output_microbe_treatment_pathways_endpoint_diversity.rds') %>% mutate()
delta_alpha = readRDS('./pathways_associations/regression_output_microbe_treatment_pathways_delta_diversity.rds') %>% mutate()

baseline_alpha
endpoint_alpha
delta_alpha
```


```{r}
# alpha diversity, interaction term model  -- baseline
setwd('~/Desktop/google_drive/My Drive/pds08/')

files = list.files('pathways_associations')
files = files[grep('baseline',files)]
files = files[grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('interaction',files)]

data = list()
for(f in files){
  d = readRDS(paste('pathways_associations/',f,sep='')) %>% mutate(var = gsub('_pathways_endpoint_diversity.rds','',gsub('regression_output_interaction_microbe_','',f)))
  data[[f]] =d
}

bind_rows(data) %>% filter(p.value<0.1)

```

```{r}
# alpha diversity, interaction term model  -- endpoint

setwd('~/Desktop/google_drive/My Drive/pds08/')

files = list.files('pathways_associations')
files = files[grep('endpoint',files)]
files = files[grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('interaction',files)]

data = list()
for(f in files){
  d = readRDS(paste('pathways_associations/',f,sep='')) %>% mutate(var = gsub('_pathways_endpoint_diversity.rds','',gsub('regression_output_interaction_microbe_','',f)))
  data[[f]] =d
}

bind_rows(data) %>% filter(p.value<0.1)
```

```{r}
# alpha diversity, interaction term model  -- delta

setwd('~/Desktop/google_drive/My Drive/pds08/')

files = list.files('pathways_associations')
files = files[grep('delta',files)]
files = files[grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('interaction',files)]

data = list()
for(f in files){
  d = readRDS(paste('pathways_associations/',f,sep='')) %>% mutate(var = gsub('_pathways_endpoint_diversity.rds','',gsub('regression_output_interaction_microbe_','',f)))
  data[[f]] =d
}

bind_rows(data) %>% filter(p.value<0.1)
```

```{r}
#FIGURE stuff to look at --

# F1 -- BASELINE ANALYSIS

# note -- will need shannon supp figs for everything

# bristol (baseline and endpoint) for simpson* and richness*

# delta_alpha for simpson and richness*


```

```{r}
get_volcanos <- function(regression_output,output_folder){
  features = unique(regression_output$var)
  for(f in features){
    data_sub = regression_output %>% filter(var==f)
    plotout = ggplot(data=data_sub,aes(x=estimate,y=-log10(bh),label=term))+geom_point()+geom_hline(yintercept = -log10(0.05),linetype='dashed') + ggtitle(f) + ylab('-log10(qval)') +ggtitle('') + xlim(-5,5) + ylim(0,11) + geom_label_repel(data = data_sub %>% arrange(bh) %>% filter(bh<0.05) %>% head(10),aes(label = term),
                  box.padding   = 0.1, 
                  point.padding = 0.1,
                  max.overlaps=100,
                  size=3,
                  segment.color = 'grey50')
    ggsave(paste(output_folder,f,'_volcano.pdf',sep=''),width=10,height=10)
  }
}
```

```{r}
# regression output -- BASELINE, CLINICAL

setwd('~/Desktop/google_drive/My Drive/pds08/pathways_associations')

files = list.files()
files = files[grep('baseline',files)]
files = files[-grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('outcome',files)]

data = list()
for(f in files){
  d = readRDS(paste(f,sep='')) %>% mutate(var = gsub('_pathways_baseline.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

baseline_pathways_merged = bind_rows(data)

get_volcanos(baseline_pathways_merged,'volcano_plots_baseline/')

```


```{r}
# regression output -- ENDPOINT, CLINICAL

setwd('~/Desktop/google_drive/My Drive/pds08/pathways_associations')

files = list.files()
files = files[grep('endpoint',files)]
files = files[-grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('outcome',files)]


data = list()
for(f in files){
  d = readRDS(paste(f,sep='')) %>% mutate(var = gsub('_pathways_endpoint.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

baseline_pathways_merged = bind_rows(data)

get_volcanos(baseline_pathways_merged,'volcano_plots_endpoint/')

```

```{r}
# regression output -- DELTA, TREATMENT

setwd('~/Desktop/google_drive/My Drive/pds08/pathways_associations')

files = list.files()
files = files[grep('endpoint',files)]
files = files[-grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('outcome',files)]

data = list()
for(f in files){
  d = readRDS(paste(f,sep='')) %>% mutate(var = gsub('_pathways_delta.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

baseline_pathways_merged = bind_rows(data)

get_volcanos(baseline_pathways_merged,'volcano_plots_delta/')

```
















```{r} 
# regression output -- BASELINE, INTERACTION

setwd('~/Desktop/google_drive/My Drive/pds08/pathways_associations')

files = list.files()
files = files[grep('baseline',files)]
files = files[-grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('interaction',files)]

data = list()
for(f in files){
  d = readRDS(paste(f,sep='')) %>% mutate(var = gsub('_pathways_baseline.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

baseline_pathways_merged = bind_rows(data)

get_volcanos(baseline_pathways_merged,'volcano_plots_baseline_interaction/')

```

```{r}
# regression output -- ENDPOINT, INTERACTION
setwd('~/Desktop/google_drive/My Drive/pds08/pathways_associations')

files = list.files()
files = files[grep('endpoint',files)]
files = files[-grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('interaction',files)]

data = list()
for(f in files){
  d = readRDS(paste(f,sep='')) %>% mutate(var = gsub('_pathways_baseline.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

baseline_pathways_merged = bind_rows(data)

get_volcanos(baseline_pathways_merged,'volcano_plots_endpoint_interaction/')

```

```{r}
# regression output -- DELTA, INTERACTION
setwd('~/Desktop/google_drive/My Drive/pds08/pathways_associations')

files = list.files()
files = files[grep('delta',files)]
files = files[-grep('diversity',files)]
files = files[grep('pathways',files)]
files = files[grep('interaction',files)]

data = list()
for(f in files){
  d = readRDS(paste(f,sep='')) %>% mutate(var = gsub('_pathways_baseline.rds','',gsub('regression_output_outcome_microbe_','',f)))
  data[[f]] =d
}

baseline_pathways_merged = bind_rows(data)

get_volcanos(baseline_pathways_merged,'volcano_plots_delta_interaction/')

```

```{r}
# regression output -- treatment

setwd('~/Desktop/google_drive/My Drive/pds08/')

baseline = readRDS('./pathways_associations/regression_output_microbe_treatment_pathways_baseline.rds') 
endpoint = readRDS('./pathways_associations/regression_output_microbe_treatment_pathways_endpoint.rds')
delta = readRDS('./pathways_associations/regression_output_microbe_treatment_pathways_delta.rds') 

baseline %>% filter(bh < 0.1)
endpoint %>% filter(bh < 0.1)
delta %>% filter(bh < 0.1)

```




